#this is the deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-aksprobes-webapp
  namespace: default
  labels:
    app: dev-aksprobes-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      service: dev-aksprobes-webapp
  template:
    metadata:
      labels:
        app: dev-aksprobes-webapp
        service: dev-aksprobes-webapp
        
    spec:
      containers:
      - name: dev-aksprobes-webapp
        image: acrmediaprodwestus3.azurecr.io/dev-kjk-repo:($tagsdsd)
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
        
      nodeSelector:
        agentpool: aksprodpool
